# Generated by Django 4.1.3 on 2022-11-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_orderitems_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
