# Generated by Django 4.1.3 on 2022-11-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_collection_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(check=models.Q(('membership__in', ['G', 'B', 'S'])), name='check_membership'),
        ),
    ]
