# Generated by Django 4.1.4 on 2022-12-30 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_alter_cart_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_cancel_order', 'can cancel order')]},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('C', 'cancel'), ('a', 'active')], default='a', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
